backend:
  name: test-repo

media_folder: assets/uploads
public_folder: /assets/uploads

collections:
  - name: test
    label: Test Content
    files:
      - name: demo
        label: Demo Page
        file: test.md
        fields:
          - label: Title
            name: title
            widget: string
          - label: Body
            name: body
            widget: markdown
